name: sparrow-pycapsule
channels:
  - conda-forge
dependencies:
  # Build
  - cmake
  - ninja
  # Dependencies
  - sparrow-devel
  - python
  - nanobind
  # Tests
  - doctest
  - polars
  - pyarrow
  - pytest
  # Documentation
  - doxygen
  - graphviz
